### ISSUE TITLE
[Question] Considerare di contribuire alla collection GitHub "Made in Italy"

### ISSUE THREAD

**Issue by TheJoin95** [italia-opensource/awesome-italia-opensource#40]
Ciao!

Qualche tempo fa, con @Wabri, in Schrodinger Hat avevamo creato la collection sull'explore di GitHub chiamata [Made in Italy](https://github.com/collections/made-in-italy).

É possible contribuire direttamente sulla repository Explore di GitHub stesso.

Mi chiedevo: merita mantenere anche quella pagina? O centralizzare le varie PR e contribution su una di queste?

**Comment by FabrizioCafolla** [comment]
Ciao, 

Ottima domanda, sinceramente non saprei.

Posso solo dire che con una repo nostra (perchè questo progetto non lo reputo solo mio ma di tutti quelli che ne vogliono far parte) sia più comoda da mantenere e gestire.

Altra cosa, questo è il primo di una serie di progetti che verranno pubblicati su questa organizzazione.

**Comment by TheJoin95** [comment]
Chiaramente la domanda è aperta a tutti i contributor della repository, se vuoi puoi creare o assegnare la label per la `question` :)

La repo di GitHub accetta comunque le PR, dietro review, e ha una contribution guideline. All'epoca ci piaceva portare un qualcosa al di fuori della nostra organizzazione, in GitHub appunto, rinunciando anche al nome stesso per l'obiettivo oggettivamente più grande.

Ho letto la descrizione dell'organizzazione, siamo allineati sia a livello personale sia come Schrodinger Hat. Non voglio uscire di contesto dalla issue, aggiungo solo che nel caso sentiti libero di raggiungere i vari canali di Schrodinger per approfondire con una chiacchierata il tutto, a me piacerebbe!

**Comment by FabrizioCafolla** [comment]
Capisco però in questo caso per come immagino le cose ha più senso avere tutto dentro l'organizzazione.

Le issue come `question` vorrei evitarle perchè penso che su discord escano più comprensibili.

Il canale è [question](https://discord.gg/JHV2WyTePG)

**Comment by TheJoin95** [comment]
Conosco molti dev che non hanno discord o che preferiscono avere una board diretta sulla repo, se le issue con le etichette vuoi evitarle magari é possibile considerare aggiungere una discussion tramite la funzionalità di GitHub stessa :)

Ad ogni modo, ho capito il tuo pensiero, valuta tu se chiudere la issue o ricevere ulteriori feedback da altri contributors ;)

**Comment by FabrizioCafolla** [comment]
Penso che tu abbia ragione, ho aggiunto la label alla issue, poi aggiungerò il template in modo da avere uno stile coerente fra le varie issue taggate come `question`
