### ISSUE TITLE
💡 [REQUEST] - Aggiunta licenze cooperative

### ISSUE THREAD

**Issue by chobeat** [italia-opensource/awesome-italia-opensource#53]
### Summary

Buongiorno.

Ho notato che nella lista delle licenze permesse mancano tutte (credo) quelle legate al copyfarleft che pur non rientrando nella definizione di free software, rientrano a pieno titolo in quello di open source.

Io ho rilasciato un software tramite una di queste licenze (coopyleft) quindi volevo sapere se si potessero aggiungere.

Per aprire la issue ho stilato una breve lista che non credo sia esaustiva ma copre quelle principali adottate nell'ambito cooperativo.

coopyleft: https://wiki.coopcycle.org/en:license
CSL: https://lynnesbian.space/csl/
PPL (Peer Production License): https://wiki.p2pfoundation.net/Peer_Production_License

Poi ci sarebbero quelle un po' più complicate che però vedete voi se aggiungerle:

CopyFair: https://wiki.p2pfoundation.net/CopyFair_License
FairSource: https://fair.io/?a

Per approfondire: https://wiki.p2pfoundation.net/copyfarleft

**Comment by FabrizioCafolla** [comment]
@chobeat Ho aggiunto le licenze indicate.

Grazie per la segnalazione
