### ISSUE TITLE
❓ [QUESTION] - Awesome "Tech Blog" e "Tech Communities" italiane

### ISSUE THREAD

**Issue by FabrizioCafolla** [italia-opensource/awesome-italia-opensource#74]
### Summary

Vorrei introdurre due nuove awesome list, quella dei Tech Blog italiani e quella delle community tech.

Vorrei iniziare a raccogliere nomi, chiunque volesse può inserirli qui come commento e inserendo i vari campi:

```
- Type: community/blog
- Name: {name}
- Url: url
- Channel: Telegram/Discord/etc.. 
```

**Comment by GuidoPenta** [comment]
Ciao Fabrizio, io ho un repo che ne contiene varie, se ti interessa :)

https://github.com/GuidoPenta/awesome-italian-tech-communities

**Comment by FabrizioCafolla** [comment]
Interessante, io vorrei replicare la stessa struttura delle company e dei progetti, in modo tale da avere dei dati strutturati.

Siccome l'idea è quella di dare una panoramica del mondo tech italiano quello delle community era qualcosa che pensavo da tempo, se vuoi, possiamo portare quelle che hai già raccolto all'interno del repository.

Ora sto lavorando la sito web appena riesco strutturo la parte delle nuove liste awesome per le community e i blog.

**Comment by GuidoPenta** [comment]
si, assolutamente! Non ho idea di come si faccia a portarlo nel tuo repo (non sono un Dev 🤣) ma attingi pure!

**Comment by FabrizioCafolla** [comment]
Guarda alla fine si tratta di salvare i dati in file json con campi chiave-valore, tipo:

```
{
  "name": "test",
  "type": "community"
}
```

Ancora devo capire come strutturare il json per queste categorie, ma comunque sia saranno file json con stessa struttura ma  valorizzati in modo diverso.

Per ora sto lavorando al sito, se vuoi vederla  (è in bozza)  [italiaopensource.com](https://italiaopensource.com/)

**Comment by GuidoPenta** [comment]
Bellissimo!
